# Start from python:3 base image
FROM python:3
ENV TZ="America/Los_Angeles"

# Make dir app
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
COPY . /app

RUN pip install -r requirements.txt
# Install vim and redis for debugging
RUN apt-get update && apt-get install -y vim redis

CMD ["sleep", "1000000"]
