version: "3.8"

services:
  dash-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    extra_hosts:
      - "alice:10.1.10.183"
      - "rosalindf:10.1.10.182"
      - "tdobz:10.1.10.205"
      - "flor:10.1.10.176"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3312
