# Start from python:3 base image
FROM python:3
ENV TZ="America/Los_Angeles"

# Make dir app
WORKDIR /app

# Install dependencies
COPY requirements.txt ./

RUN pip install -r requirements.txt

# Run the executable
CMD ["python", "monitor.py"]
