version: "3.4"

services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile.monitor

    restart: always
    depends_on:
      - mysql
    volumes:
        - ~/.ssh:/root/.ssh
        - .:/app
    links:
      - mysql:mysql
    extra_hosts:
     - "alice:10.1.10.183"
     - "rosalindf:10.1.10.182"
     - "tdobz:10.1.10.205"
     - "flor:10.1.10.176"
    networks:
      - python


#
  mysql:
    restart: always
    image: mysql:8
    container_name: mysql
    command: "--mysql-native-password=ON"
#    command: "--default-authentication-plugin=mysql_native_password"

    volumes:
      - ./data:/var/lib/mysql:delegated
#      - ./MonarchBackup2022-01-12.sql:/docker-entrypoint-initdb.d/MonarchBackup2022-01-12.sql

    environment:
      MYSQL_ROOT_PASSWORD: qhALiqwRFNlOzwqnbXgGbKpgCZXUiSZvmAsRLlFIIMqjSQrf
      MYSQL_DATABASE: load
      TZ: America/Los_Angeles
      MYSQL_TCP_PORT: 3312

    ports:
      - "3312:3312"
    networks:
      - python

networks:
  python:
    driver: bridge



